import { createTypes } from 'redux-sauce';

export default createTypes(`
  ITINERARIES_LIST_REQUEST
  ITINERARIES_LIST_SUCCESS
  ITINERARIES_LIST_FAILURE

  ITINERARIES_GET_REQUEST
  ITINERARIES_GET_SUCCESS
  ITINERARIES_GET_FAILURE
`);